name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'   # run on version tags

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
          signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}

      - name: Grant execute permission for gradlew
        # On Windows, just run gradlew directly, no need for chmod
        run: echo "No chmod needed on Windows"

      - name: Publish to Maven Central
        #run: .\gradlew.bat publish
       # env:
          #OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          #OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          #GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          #GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
